version: "3.9"
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "cookhub"
      POSTGRES_USER: "usr"
      POSTGRES_PASSWORD: "pwd"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: