-- Создание таблицы пользователей
CREATE TABLE cookhub_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    activation_code VARCHAR(255),
    active BOOLEAN,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);

-- Создание таблицы ролей пользователей
CREATE TABLE cookhub_user_role (
    cookhub_user_id BIGINT NOT NULL,
    role VARCHAR(255) CHECK (role IN ('USER', 'ADMIN')),
    PRIMARY KEY (cookhub_user_id, role)
);

-- Создание таблицы рецептов
CREATE TABLE recipe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category VARCHAR(255) CHECK (category IN ('SOUPS', 'SALADS', 'DESSERTS', 'MAIN_COURSES')),
    filename VARCHAR(255),
    text TEXT NOT NULL,
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- Создание таблицы подписчиков
CREATE TABLE cookhub_user_follower (
    follower_id BIGINT,
    following_id BIGINT,
    PRIMARY KEY (follower_id, following_id)
);

-- Создание внешних ключей
ALTER TABLE IF EXISTS cookhub_user_role
    ADD CONSTRAINT cookhub_user_role_user_fk
    FOREIGN KEY (cookhub_user_id)
    REFERENCES cookhub_user (id);

ALTER TABLE IF EXISTS recipe
    ADD CONSTRAINT recipe_user_fk
    FOREIGN KEY (user_id)
    REFERENCES cookhub_user (id);

ALTER TABLE IF EXISTS cookhub_user_follower
    ADD CONSTRAINT cookhub_user_follower_user_fk1
    FOREIGN KEY (follower_id)
    REFERENCES cookhub_user (id);

ALTER TABLE IF EXISTS cookhub_user_follower
    ADD CONSTRAINT cookhub_user_follower_user_fk2
    FOREIGN KEY (following_id)
    REFERENCES cookhub_user (id);
